spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_jwtauthsvr
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: localhost
    port: 6379
  sql:
    init:
      platform: postgresql
      mode: never
jwt:
  secret:
    access: cue+IftBIPyaeLyoGfZ6ZtukljcGc4EyvmKyA+AWauwD8REzjU808w0ig36JBp7Hs3Qn+voDNkwZQpbrI5WwCw==
    refresh: d2OFrL5/Vvp7rFHCq0jaFXUnMbwDg3RixYy6cF1vIIjXTO+xrDRRokF3ZK8NZ4kFPpSNYDxqICCWvBtYzzrRfw==
  duration:
    access-token: 5
    refresh-token: 30
redis:
  duration:
    value: 30
